flask_blog/blog/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Save')
    picture = FileField('Добавить изображение для заголовка поста',
                        validators=[FileAllowed(['jpg', 'png']), DataRequired()])

flask_blog/blog/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.blog.forms import PostForm
from flask_blog.users.utils import save_blog_picture

blog = Blueprint('blog', __name__)


@blog.route("/blog")
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=6)
    return render_template('blog.html', posts=posts)


@blog.route("/new_post", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        picture_file = save_blog_picture(form.picture.data)

        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user, image_file=picture_file)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('blog.allpost'))
    return render_template('create_post.html',
                           title='Новый пост', form=form, legend='Новый пост')


@blog.route("/post_<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@blog.route("/post_<int:post_id>_update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('blog.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Обновление поста',
                           form=form, legend='Обновление поста')


@blog.route("/post_<int:post_id>_delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('blog.allpost'))

flask_blog/portfolio/routes.py
from flask import render_template, Blueprint

portfolio = Blueprint('portfolio', __name__)

@portfolio.route("/portfolio")
def portfolio_main():
    return render_template('portfolio.html')

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, \
    RequestResetForm, ResetPasswordForm
from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана!'
              ' Теперь вы можете войти в систему', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)

            return redirect(url_for('main.home'))
        else:
            flash('Войти не удалось. Пожалуйста, '
                  'проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user) \
            .order_by(Post.date_posted.desc()) \
            .paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' +
                                            current_user.image_file)
    return render_template('account.html', title='Аккаунт',
                           image_file=image_file, form=form, posts=posts,
                           user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user_<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('users_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с '
              'инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt. \
            generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! '
              'Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Сброс пароля', form=form)

flask_blog/templates/account.html
{% extends "layout.html" %}

{% block title %}
{{ current_user.username }} account
{% endblock %}

{% block navi %}
<a href="/" class="nav-link">HOME</a>
<a href="portfolio" class="nav-link">PORTFOLIO</a>
<a href="blog" class="nav-link">BLOG</a> |
{% if current_user.is_authenticated %}
<a href="account" class="nav-link active">ACCOUNT</a>
<a href="logout" class="nav-link">LOGOUT</a>
{% else %}
<a href="login" class="nav-link">LOGIN</a>
<a href="register" class="nav-link">REGISTER</a>
{% endif %}
{% endblock %}

{% block content %}
<div class="content-section">
    <div class="media" style="text-align: center">


        <div class="media-body">
            <img class="rounded-circle account-img" src="{{ image_file }}"><br><br>
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <br>
    <br>
    <br>

    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update account data</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}

                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-download-cv btn-primary rounded-pill") }}
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/blog.html
{% extends "layout.html" %}

{% block title %}
    Sergey Kosarev :: blog
{% endblock %}

{% block navi %}
    <a href="/" class="nav-link">HOME</a>
    <a href="portfolio" class="nav-link">PORTFOLIO</a>
    <a href="blog" class="nav-link active">BLOG</a> |
    {% if current_user.is_authenticated %}
        <a href="account" class="nav-link">ACCOUNT</a>
        <a href="logout" class="nav-link">LOGOUT</a>
    {% else %}
        <a href="login" class="nav-link">LOGIN</a>
        <a href="register" class="nav-link">REGISTER</a>
    {% endif %}
{% endblock %}

{% block content %}

    <section class="blog-section">
        <div class="blog-posts-wrapper">
            <div>
                <h2 class="section-title">Curious about IT or break into the industry</h2>
            </div>
            <div class="pull-right">
                {% if current_user.is_authenticated %}
                    <a class="btn btn-download-cv btn-primary rounded-pill" href="/new_post">Create Post
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="blog-posts-wrapper">
            {% for post in posts.items %}

                <article class="blog-post">
                    <a href="{{ url_for('blog.post', post_id=post.id) }}" class="blog-post-link">
                        <img src="blog_pics/{{ post.image_file }}" class="blog-post-thumbnail">

                        <h5 class="blog-post-title">{{ post.title }}</h5>

                    </a>
                    <p class="blog-post-meta">
                        <span class="post-published-date">{{ post.date_posted.strftime('%Y-%m-%d %H:%M') }}</span>
                        {#                    <a href="#!" class="post-comments">3 COMMENTS</a>#}
                    </p>
                </article>

            {% endfor %}
        </div>
        <div class="pull-right">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <a class="btn btn-success mb-4"
                           href="{{ url_for('blog.allpost', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-success mb-4"
                           href="{{ url_for('blog.allpost', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </section>

{% endblock %}
{% block script %}
    <script src="assets/vendors/entry/jq.entry.min.js"></script>
{% endblock %}

flask_blog/templates/create_post.html
{% extends "layout.html" %}

{% block title %}
    create post
{% endblock %}

{% block navi %}
    <a href="/" class="nav-link">HOME</a>

    <a href="portfolio" class="nav-link">PORTFOLIO</a>
    <a href="blog" class="nav-link active">BLOG</a> |
    {% if current_user.is_authenticated %}
        <a href="account" class="nav-link">ACCOUNT</a>
        <a href="logout" class="nav-link">LOGOUT</a>
    {% else %}
        <a href="login" class="nav-link">LOGIN</a>
        <a href="register" class="nav-link">REGISTER</a>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="content-section">

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New Post</legend>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}

                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-download-cv btn-primary rounded-pill") }}
            </div>
        </form>

{% endblock content %}

flask_blog/templates/home.html
{% extends "layout.html" %}

{% block content %}
<aside>
<section class="registration-section">
    <h2 class="section-title">Hello{% if current_user.is_authenticated %}, {{
        current_user.username }}{% endif %}!</h2>
    <p>I am Sergey Kosarev, python developer.
        I improve skills in Python, including OOP, Django Framework and DRF, Flask,
        FastAPI, Scrapy, Scikit-learn; as well as JavaScript, SQL, etc. I have other hard
        skills. This site was created to showcase my portfolio. If you are ready to offer a
        Python-developer, data-scientist, analyst or similar job, you can contact me
        through any of the contacts provided. I will be glad to answer all your
        questions.</p>
    <a href="register" class="btn btn-primary btn-hire-me">HIRE ME</a>
</section>
<section class="resume-section">
    <div class="row">
        <div class="col-lg-6">
            <br><h6 class="section-subtitle">RESUME</h6>
            <h2 class="section-title">EDUCATION</h2>
            <ul class="time-line">
                <li class="time-line-item">
                    <span class="badge badge-primary">2021 — 2022</span>
                    <h6 class="time-line-item-title">Python developer</h6>
                    <p class="time-line-item-subtitle">GeekBrains University, gb.ru
                        (mail.ru company)</p>
                    <p class="time-line-item-content">Django, Flask, REST, WSGI, JS, SQL, HTML</p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2006 - 2009</span>
                    <h6 class="time-line-item-title">Lawyer</h6>
                    <p class="time-line-item-subtitle">Volga State Academy of Water
                        Transport, Nizhny Novgorod</p>
                    <p class="time-line-item-content"> Jurisprudence
                    </p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2003 - 2008</span>
                    <h6 class="time-line-item-title">Company manager</h6>
                    <p class="time-line-item-subtitle">Volga State Academy of Water
                        Transport, Nizhny Novgorod</p>
                    <p class="time-line-item-content">Economics, management
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-6">
            <h6 class="section-subtitle">RESUME</h6>
            <h2 class="section-title">Experience</h2>
            <ul class="time-line">
                <li class="time-line-item">
                    <span class="badge badge-primary">2022</span>
                    <h6 class="time-line-item-title">Python Developer</h6>
                    <p class="time-line-item-content">Self-employment / freelancing / startups /
                        internships</p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2017 - 2022</span>
                    <h6 class="time-line-item-title">Business development director</h6>
                    <p class="time-line-item-subtitle">Federal real estate agency</p>
                    <p class="time-line-item-content">Analytics, sales planning, opening of
                        new sales offices.
                    </p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2013 - 2017</span>
                    <h6 class="time-line-item-title">Deputy Director</h6>
                    <p class="time-line-item-subtitle">House management company of the city
                        district</p>
                    <p class="time-line-item-content">Financial analytics, modeling,
                        control of results. Ensuring financial stability and economic development
                        of the enterprise.
                    </p>
                </li>
                <li class="time-line-item">
                    <span class="badge badge-primary">2008 - 2013</span>
                    <h6 class="time-line-item-title">Various positions in construction
                        and communal services</h6>
                </li>
            </ul>
        </div>
    </div>
</section>
</aside>
{% endblock content %}

flask_blog/templates/login.html
{% extends "layout.html" %}

{% block navi %}
    <a href="/" class="nav-link ">HOME</a>
    <a href="portfolio" class="nav-link">PORTFOLIO</a>
    <a href="blog" class="nav-link">BLOG</a> |
    {% if current_user.is_authenticated %}
    <a href="account" class="nav-link">ACCOUNT</a>
    <a href="logout" class="nav-link">LOGOUT</a>
    {% else %}
    <a href="login" class="nav-link active">LOGIN</a>
    <a href="register" class="nav-link">REGISTER</a>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-download-cv btn-primary rounded-pill") }}
                <small class="text-muted ml-2">
                     <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Do not have an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
            </small>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/post.html
{% extends "layout.html" %}

{% block title %}
    post
{% endblock %}

{% block navi %}
    <a href="/" class="nav-link">HOME</a>

    <a href="portfolio" class="nav-link">PORTFOLIO</a>
    <a href="blog" class="nav-link active">BLOG</a> |
    {% if current_user.is_authenticated %}
        <a href="account" class="nav-link">ACCOUNT</a>
        <a href="logout" class="nav-link">LOGOUT</a>
    {% else %}
        <a href="login" class="nav-link">LOGIN</a>
        <a href="register" class="nav-link">REGISTER</a>
    {% endif %}
{% endblock %}

{% block content %}
    <section class="blog-section">
        <div class="blog-posts-wrapper">
            <div>
                <h4 class="card-title">{{ post.title }}</h4>
            </div>
            <div class="pull-right">
                {% if post.author == current_user %}
                    {% if post.author == current_user %}
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{{ url_for('blog.update_post', post_id=post.id) }}">update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                                data-target="#deleteModal">delete
                        </button>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <div class="blog-posts-wrapper">
            <article class="blog-post-pic">
                <img src="blog_pics/{{ post.image_file }}" class="blog-post-thumbnail">
            </article>
            <article class="blog-post-text pull-left">
                <p class="card-text">{{ post.content }}</p>
                <small>{{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}

                    <br> Author: <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
                                    style="margin: 0 auto">{{ post.author.username }}</a>
                <br>
                    <img class="rounded-circle article-img" style="margin-right: 5px;"
                         src="{{ url_for('static', filename='profile_pics/' +
		post.author.image_file) }}">
                </small>
            </article>
        </div>


        <!-- <i class="fa fa-heart-o"></i>
        <i class="fa fa-bookmark-o"></i> -->


        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <form action="{{ url_for('blog.delete_post', post_id=post.id) }}" method="POST">
                            <input class="btn btn-danger" type="submit" value="Удалить">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

flask_blog/templates/users_posts.html
{% extends "layout.html" %}

{% block title %}
    post
{% endblock %}

{% block navi %}
    <a href="/" class="nav-link">HOME</a>

    <a href="portfolio" class="nav-link">PORTFOLIO</a>
    <a href="blog" class="nav-link active">BLOG</a> |
    {% if current_user.is_authenticated %}
        <a href="account" class="nav-link">ACCOUNT</a>
        <a href="logout" class="nav-link">LOGOUT</a>
    {% else %}
        <a href="login" class="nav-link">LOGIN</a>
        <a href="register" class="nav-link">REGISTER</a>
    {% endif %}
{% endblock %}

{% block content %}
    <section class="blog-section">

        {#            <article class="media" style="display: flex; flex-direction: column;">#}
        {#                <img class="rounded-circle article-img" style="margin-right: 5px;"#}
        {#                     src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">#}
        {#                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"#}
        {#                   style="margin: 0 auto">{{ post.author.username }}</a>#}
        {#            </article>#}
        <div class="blog-posts-wrapper">
            <h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
            {% for post in posts.items %}
                <div class="container" style="display: flex;">
                    <article class="media" style="display: flex; flex-direction: column;">
                        <img class="rounded-circle article-img" style="margin-right: 5px;"
                             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
                           style="margin: 0 auto">{{ post.author.username }}</a>
                    </article>

                    <div class="card" style="margin-bottom: 20px;">
                        <div class="card-body">
                            <h4 class="card-title"><a class="title"
                                                      href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
                            </h4>

                            <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                            <br>
                            <br>
                            <p class="card-text">{{ post.content }}</p>
                        </div>
                        <!-- <div class="card-footer" style="font-size: 20px;">
                          <i class="fa fa-heart-o"></i>
                          <i class="fa fa-bookmark-o"></i>
                        </div> -->
                    </div>
                </div>
            {% endfor %}


            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <a class="btn btn-success mb-4"
                           href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-success mb-4"
                           href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>

    </section>

{% endblock content %}